# Generated by Django 2.2.1 on 2019-05-03 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_picture',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
