# Generated by Django 2.2 on 2019-05-01 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product_picture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Products'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='exchange.Products'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='with_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='with_product', to='exchange.Products'),
        ),
    ]
