# Generated by Django 2.2.1 on 2019-05-01 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0002_auto_20190501_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Phones',
            new_name='Phone',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
