# Generated by Django 2.2 on 2019-05-01 01:45

from django.db import migrations, models
import exchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', exchange.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
