# Generated by Django 2.2.1 on 2019-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20190503_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_picture',
            name='picture_path',
            field=models.FileField(upload_to='product_images/'),
        ),
    ]
