# Generated by Django 2.2.1 on 2019-05-04 02:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20190503_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_picture',
            name='picture_path',
            field=models.ImageField(upload_to='product_images'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_accept', models.BooleanField(null=True)),
                ('offerer_accept', models.BooleanField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expired_datetime', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_product', to='exchange.Product')),
                ('with_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_with_product', to='exchange.Product')),
            ],
        ),
    ]
