# Generated by Django 2.2.1 on 2019-05-04 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20190504_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='with_product',
        ),
        migrations.AlterField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Product'),
        ),
        migrations.CreateModel(
            name='DealOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Deal')),
                ('offer_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Product')),
            ],
        ),
    ]
