# Generated by Django 2.2.1 on 2019-05-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20190504_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_cancel',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
