# Generated by Django 2.2.1 on 2019-05-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20190505_0547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exchange',
        ),
    ]
