# Generated by Django 2.2.1 on 2019-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(default=None, max_length=225),
            preserve_default=False,
        ),
    ]
