# Generated by Django 2.2.1 on 2019-05-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_firebase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
