# Generated by Django 2.2.1 on 2019-05-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190506_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=None, upload_to='profile'),
            preserve_default=False,
        ),
    ]
